@baseUrl = http://localhost:8080/api/v1
@deviceId = esp32-test-device-01
@apiKey = test-key


### Health Check 
GET {{baseUrl}}/health


### Get Current Page
GET {{baseUrl}}/current_page
X-Device-Id: {{deviceId}}
Authorization: Bearer {{apiKey}}

### Push Button
POST {{baseUrl}}/push_button
X-Device-Id: {{deviceId}}
Authorization: Bearer {{apiKey}}

{
    "button_id": "A",
    "type": "short_press"
}

### Long Button press
POST {{baseUrl}}/push_button
X-Device-Id: {{deviceId}}
Authorization: Bearer {{apiKey}}

{
    "button_id": "E",
    "type": "long_press"
}
